name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - run: |
          npm ci
          cd packages/test
          npm publish --tag rc 
