name: Publish

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: https://npm.pkg.github.com
      - run: |
          npm ci
          cd packages/test
          npm publish --tag rc 
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
